/*
 Copyright (c) Microsoft Corporation.  All rights reserved.
 This code is licensed by Microsoft Corporation under the terms
 of the MICROSOFT REACTIVE EXTENSIONS FOR JAVASCRIPT AND .NET LIBRARIES License.
 See http://go.microsoft.com/fwlink/?LinkID=220762.
*/
(function(){var Y,K,E,T,o,ia,Z,z;E=this;ia=function(){};K=function(){return(new Date).getTime()};Y=function(b,a){return b===a};T=function(b){return b};Z=function(b){return b.toString()};o="undefined"===typeof ProvideCustomRxRootObject?E.Rx={}:ProvideCustomRxRootObject();o.VERSION="<%= RXJS_VERSION %>";var Fa=Object.prototype.hasOwnProperty,r=function(b,a){function c(){this.constructor=b}for(var d in a)Fa.call(a,d)&&(b[d]=a[d]);c.prototype=a.prototype;b.prototype=new c;b.__super__=a.prototype;return b};
z=Array.prototype.slice;var v,ja;ja=function(b){var a,c;a=[];for(c=0;c<b.length;c++)a.push(b[c]);return a};v=o.List=function(){function b(a){this.comparer=a||Y;this.count=0;this.items=[]}b.prototype.Add=function(a){this.items[this.count]=a;this.count++};b.prototype.RemoveAt=function(a){if(0>a||a>=this.count)throw"Index of out range";0===a?this.items.shift():this.items.splice(a,1);this.count--};b.prototype.IndexOf=function(a){var c,b;for(c=0;c<this.items.length;c++)if(b=this.items[c],this.comparer(a,
b))return c;return-1};b.prototype.Remove=function(a){a=this.IndexOf(a);if(-1===a)return!1;this.RemoveAt(a);return!0};b.prototype.Clear=function(){this.items=[];this.count=0};b.prototype.Count=function(){return this.count};b.prototype.Item=function(a,c){if(0>a||a>=count)throw"Index of out range";return void 0===c?this.items[a]:this.items[a]=c};b.prototype.ToArray=function(){var a,c;a=[];for(c=0;c<this.items.length;c++)a.push(this.items[c]);return a};b.prototype.Contains=function(a){var c,b;for(b=0;b<
this.items.length;b++)if(c=this.items[b],this.comparer(a,c))return!0;return!1};return b}();var ka,U,$;$=function(b,a,c,d,e){for(;0<e;)c[e+d-1]=b[e+a-1],e--};ka=function(){function b(a,c){this.Id=a;this.Value=c}b.prototype.CompareTo=function(a){var c;c=this.Value.CompareTo(a.Value);0===c&&(c=this.Id-a.Id);return c};return b}();U=function(){function b(a){this.items=Array(a);this.size=0}b.prototype.IsHigherPriority=function(a,c){return 0>this.items[a].CompareTo(this.items[c])};b.prototype.Percolate=
function(a){var c,b;if(!(a>=this.size||0>a))if(c=Math.floor((a-1)/2),!(0>c||c===a)&&this.IsHigherPriority(a,c))b=this.items[a],this.items[a]=this.items[c],this.items[c]=b,this.Percolate(c)};b.prototype.Heapify=function(a){var c,b,e;void 0===a&&(a=0);a>=this.size||0>a||(b=2*a+1,e=2*a+2,c=a,b<this.size&&this.IsHigherPriority(b,c)&&(c=b),e<this.size&&this.IsHigherPriority(e,c)&&(c=e),c!==a&&(b=this.items[a],this.items[a]=this.items[c],this.items[c]=b,this.Heapify(c)))};b.prototype.Peek=function(){return this.items[0].Value};
b.prototype.Count=function(){return this.size};b.prototype.RemoveAt=function(a){this.items[a]=this.items[--this.size];delete this.items[this.size];this.Heapify();if(this.size<this.items.length>>2)a=this.items,this.items=Array(this.items.length>>1),$(a,0,this.items,0,this.size)};b.prototype.Dequeue=function(){var a;a=this.Peek();this.RemoveAt(0);return a};b.prototype.Enqueue=function(a){var c;if(this.size>=this.items.length)c=this.items,this.items=Array(2*this.items.length),$(c,0,this.items,0,c.length);
c=this.size++;this.items[c]=new ka(b.count++,a);this.Percolate(c)};b.prototype.Remove=function(a){var c;for(c=0;c<this.size;c++)if(this.items[c].Value===a)return this.RemoveAt(c),!0;return!1};return b}();U.count=0;var q;q=o.CompositeDisposable=function(){function b(){var a;this.disposed=!1;this.disposables=new v;for(a=0;a<arguments.length;a++)this.disposables.Add(arguments[a])}b.prototype.Count=function(){return this.disposables.Count()};b.prototype.Add=function(a){this.disposed?a.Dispose():this.disposables.Add(a)};
b.prototype.Remove=function(a){var c;c=!1;this.disposed||(c=this.disposables.Remove(a));c&&a.Dispose();return c};b.prototype.Dispose=function(){var a,c;if(!this.disposed)this.disposed=!0,a=this.disposables.ToArray(),this.disposables.Clear();if(void 0!==a)for(c=0;c<a.length;c++)a[c].Dispose()};b.prototype.Clear=function(){var a,c;a=this.disposables.ToArray();this.disposables.Clear();for(c=0;c<a.length;c++)a[c].Dispose()};b.prototype.Contains=function(a){return this.disposables.Contains(a)};b.prototype.IsDisposed=
function(){return this.disposed};b.prototype.ToArray=function(){return this.disposables.ToArray()};return b}();var L,A,y;L=o.Disposable={Create:function(b){return{isDisposed:!1,Dispose:function(){if(!this.isDisposed)b(),this.isDisposed=!0}}},Empty:{Dispose:function(){}}};A=L.Create;y=L.Empty;var s;s=o.SingleAssignmentDisposable=function(){function b(){this.disposed=!1;this.current=null}b.prototype.IsDisposed=function(){return this.disposed};b.prototype.Disposable=function(a){var c;if(void 0===a)return this.current;
if(null!==this.current)throw"Disposable has already been assigned";c=this.disposed;if(!c)this.current=a;c&&null!==a&&a.Dispose()};b.prototype.Dispose=function(){var a;a=null;if(!this.disposed)this.disposed=!0,a=this.current,this.current=null;null!==a&&a.Dispose()};return b}();var w;w=o.SerialDisposable=function(){function b(){this.disposed=!1;this.current=null}b.prototype.IsDisposed=function(){return this.disposed};b.prototype.Disposable=function(a){var c,b;if(void 0===a)return this.current;b=this.disposed;
c=null;if(!b)c=this.current,this.current=a;null!==c&&c.Dispose();b&&null!==a&&a.Dispose()};b.prototype.Dispose=function(){var a;a=null;if(!this.disposed)this.disposed=!0,a=this.current,this.current=null;if(null!==a)return a.Dispose()};return b}();var la,M;la=function(){function b(a){this.disposable=a;this.isInnerDisposed=!1;this.disposable.count++}b.prototype.Dispose=function(){var a;a=!1;if(!this.disposable.isUnderlyingDisposed&&!this.isInnerDisposed&&(this.isInnerDisposed=!0,this.disposable.count--,
0===this.disposable.count&&this.disposable.isPrimaryDisposed))a=this.disposable.isUnderlyingDisposed=!0;if(a)return this.disposable.underlyingDisposable.Dispose()};return b}();M=o.RefCountDisposable=function(){function b(a){this.underlyingDisposable=a;this.isPrimaryDisposed=this.isUnderlyingDisposed=!1;this.count=0}b.prototype.Dispose=function(){var a;a=!1;if(!this.isUnderlyingDisposed&&!this.isPrimaryDisposed&&(this.isPrimaryDisposed=!0,0===this.count))a=this.isUnderlyingDisposed=!0;if(a)return this.underlyingDisposable.Dispose()};
b.prototype.GetDisposable=function(){return this.isUnderlyingDisposed?y:new la(this)};b.prototype.IsDisposed=function(){return this.isUnderlyingDisposed};return b}();var aa;aa=function(){function b(a,c,b,e,f){this.scheduler=a;this.state=c;this.action=b;this.DueTime=e;this.comparer=f||function(a,c){return a-c};this.Disposable=new s}b.prototype.Invoke=function(){return this.Disposable.Disposable(this.InvokeCore())};b.prototype.CompareTo=function(a){return this.comparer(this.DueTime,a.DueTime)};b.prototype.IsCancelled=
function(){return this.Disposable.IsDisposed()};b.prototype.InvokeCore=function(){return this.action(this.scheduler,this.state)};return b}();var p;p=o.Scheduler=function(){function b(a,c,b,e){this.Now=a;this.schedule=c;this.scheduleRelative=b;this.scheduleAbsolute=e}b.prototype.Schedule=function(a){return this.schedule(a,b.Invoke)};b.prototype.ScheduleWithState=function(a,c){return this.schedule(a,c)};b.prototype.ScheduleWithRelative=function(a,c){return this.scheduleRelative(c,a,b.Invoke)};b.prototype.ScheduleWithRelativeAndState=
function(a,c,b){return this.scheduleRelative(a,c,b)};b.prototype.ScheduleWithAbsolute=function(a,c){return this.scheduleAbsolute(c,a,b.Invoke)};b.prototype.ScheduleWithAbsoluteAndState=function(a,c,b){return this.scheduleAbsolute(a,c,b)};b.prototype.ScheduleRecursive=function(a){return this.ScheduleRecursiveWithState(a,function(a,b){a(function(){b(a)})})};b.prototype.ScheduleRecursiveWithState=function(a,c){return this.ScheduleWithState({First:a,Second:c},function(a,c){return b._InvokeRec1(a,c)})};
b.prototype.ScheduleRecursiveWithRelative=function(a,c){return this.ScheduleRecursiveWithRelativeAndState(c,a,function(a,c){a(function(b){c(a,b)})})};b.prototype.ScheduleRecursiveWithRelativeAndState=function(a,c,d){return this.scheduleRelative({First:a,Second:d},c,function(a,c){return b._InvokeRec2(a,c)})};b.prototype.ScheduleRecursiveWithAbsolute=function(a,c){return this.ScheduleRecursiveWithAbsoluteAndState(c,a,function(a,c){a(function(b){c(a,b)})})};b.prototype.ScheduleRecursiveWithAbsoluteAndState=
function(a,c,d){return this.scheduleAbsolute({First:a,Second:d},c,function(a,c){return b._InvokeRec3(a,c)})};return b}();p.Now=K;var ba=p.Normalize=function(b){0>b&&(b=0);return b};p.Invoke=function(b,a){a();return y};p._InvokeRec1=function(b,a){var c,d,e,f;d=new q;f=a.First;c=a.Second;e=null;e=function(a){c(a,function(a){var c,f,i;i=f=!1;c=null;c=b.ScheduleWithState(a,function(a,b){f?d.Remove(c):i=!0;e(b);return y});i||(d.Add(c),f=!0)})};e(f);return d};p._InvokeRec2=function(b,a){var c,d,e,f;d=new q;
f=a.First;c=a.Second;e=function(a){c(a,function(a,c){var f,i,g;g=i=!1;f=b.ScheduleWithRelativeAndState(a,c,function(a,c){i?d.Remove(f):g=!0;e(c);return y});g||(d.Add(f),i=!0)})};e(f);return d};p._InvokeRec3=function(b,a){var c,d,e,f;d=new q;f=a.First;c=a.Second;e=function(a){c(a,function(a,c){var f,i,g;g=i=!1;f=b.ScheduleWithAbsoluteAndState(a,c,function(a,c){i?d.Remove(f):g=!0;e(c);return y});g||(d.Add(f),i=!0)})};e(f);return d};p.Create=function(b,a,c,d){return new (function(){function a(){a.__super__.constructor.apply(this,
arguments)}r(a,p);return a}())(b,a,c,d)};var g,B;g=function(){function b(){var a;a=this;b.__super__.constructor.call(this,K,function(c,b){return b(a,c)},function(c,b,e){for(;0<ba(b););return e(a,c)},function(c,b,e){return a.ScheduleWithRelativeAndState(c,b-a.Now(),e)})}r(b,p);return b}();B=p.Immediate=new g;var ma,G,C;ma=function(){function b(){G.queue=new U(4)}b.prototype.Dispose=function(){G.queue=null};b.prototype.Run=function(){var a,c;for(c=G.queue;0<c.Count();)if(a=c.Dequeue(),!a.IsCancelled()){for(;0<
a.DueTime-p.Now(););a.IsCancelled()||a.Invoke()}};return b}();G=function(){function b(){var a;a=this;b.__super__.constructor.call(this,K,function(c,b){return a.ScheduleWithRelativeAndState(c,0,b)},function(c,d,e){d=a.Now()+ba(d);c=new aa(a,c,e,d);e=b.queue;if(null===e){e=new ma;try{b.queue.Enqueue(c),e.Run()}finally{e.Dispose()}}else e.Enqueue(c);return c.Disposable},function(c,b,e){return a.ScheduleWithRelativeAndState(c,b-a.Now(),e)})}r(b,p);b.prototype.ScheduleRequired=function(){return null===
b.queue};b.prototype.EnsureTrampoline=function(a){return this.ScheduleRequired()?this.Schedule(a):a()};return b}();G.queue=null;C=p.CurrentThread=new G;o.VirtualTimeScheduler=function(){function b(a,c){var d;this.Clock=a;this.Comparer=c;this.IsEnabled=!1;d=this;b.__super__.constructor.call(this,function(){return d.ToDateTimeOffset(d.Clock)},function(a,c){return d.ScheduleAbsolute(a,d.Clock,c)},function(a,c,b){return d.ScheduleRelative(a,d.ToRelative(c),b)},function(a,c,b){return d.ScheduleRelative(a,
d.ToRelative(c-d.Now()),b)});this.queue=new U(1024)}r(b,p);b.prototype.ScheduleRelative=function(a,c,b){c=this.Add(this.Clock,c);return this.ScheduleAbsolute(a,c,b)};b.prototype.Start=function(){var a;if(!this.IsEnabled){this.IsEnabled=!0;do if(a=this.GetNext(),null!==a){if(0<this.Comparer(a.DueTime,this.Clock))this.Clock=a.DueTime;a.Invoke()}else this.IsEnabled=!1;while(this.IsEnabled)}};b.prototype.Stop=function(){return this.IsEnabled=!1};b.prototype.AdvanceTo=function(a){var c;if(0<=this.Comparer(this.Clock,
a))throw"Argument out of range";if(!this.IsEnabled){this.IsEnabled=!0;do if(c=this.GetNext(),null!==c&&0>=this.Comparer(c.DueTime,a)){if(0<this.Comparer(c.DueTime,this.Clock))this.Clock=c.DueTime;c.Invoke()}else this.IsEnabled=!1;while(this.IsEnabled);return this.Clock=a}};b.prototype.AdvanceBy=function(a){a=this.Add(Clock,a);if(0<=this.Comparer(this.Clock,a))throw"Argument out of range";return this.AdvanceTo(a)};b.prototype.GetNext=function(){for(var a;0<this.queue.Count();)if(a=this.queue.Peek(),
a.IsCancelled())this.queue.Dequeue();else return a;return null};b.prototype.ScheduleAbsolute=function(a,c,b){var e,f;e=this;f=new aa(e,a,function(a,c){e.queue.Remove(f);return b(a,c)},c,e.Comparer);e.queue.Enqueue(f);return f.Disposable};return b}();var u;g=function(){function b(){var a;a=this;b.__super__.constructor.call(this,K,function(c,b){var e;e=E.setTimeout(function(){b(a,c)},0);return A(function(){E.clearTimeout(e)})},function(c,b,e){var f,b=ba(b);f=E.setTimeout(function(){e(a,c)},b);return A(function(){E.clearTimeout(f)})},
function(c,b,e){return a.ScheduleWithRelativeAndState(c,b-a.Now(),e)})}r(b,p);return b}();p.Timeout=new g;u=p.Timeout;var n;n=o.Notification=function(){function b(){}b.prototype.Accept=function(a,c,b){return 1<arguments.length||"function"===typeof a?this._Accept(a,c,b):this._AcceptObservable(a)};b.prototype.ToObservable=function(a){var c;c=this;a=a||p.Immediate;return h(function(b){return a.Schedule(function(){c._AcceptObservable(b);"N"===c.Kind()&&b.OnCompleted()})})};b.prototype.HasValue=function(){return!1};
b.prototype.Value=function(){return null};b.prototype.Exception=function(){return null};b.prototype.Equals=function(a){return this.toString()===(void 0===a||null===a?"":a.toString())};return b}();n.CreateOnNext=function(b){var a=new n;a.Value=function(){return b};a.HasValue=function(){return!0};a.Kind=function(){return"N"};a._Accept=function(a){return a(this.Value())};a._AcceptObservable=function(a){return a.OnNext(this.Value())};a.toString=function(){return"OnNext("+this.Value()+")"};return a};n.CreateOnError=
function(b){var a=new n;a.Exception=function(){return b};a.Kind=function(){return"E"};a._Accept=function(a,b){return b(this.Exception())};a._AcceptObservable=function(a){return a.OnError(this.Exception())};a.toString=function(){return"OnError("+this.Exception()+")"};return a};n.CreateOnCompleted=function(){var b=new n;b.Kind=function(){return"C"};b._Accept=function(a,b,d){return d()};b._AcceptObservable=function(a){return a.OnCompleted()};b.toString=function(){return"OnCompleted()"};return b};var H;
H=function(){};g=H.prototype;g.Concat=function(){var b;b=this;return h(function(a){var c,d,e,f;e=!1;d=b.GetEnumerator();f=new w;c=p.Immediate.ScheduleRecursive(function(b){var c,F,l;l=!1;if(!e){try{if(l=d.MoveNext())c=d.Current}catch(m){F=m}void 0!==F?a.OnError(F):l?(F=new s,f.Disposable(F),F.Disposable(c.Subscribe(function(b){return a.OnNext(b)},function(b){return a.OnError(b)},function(){return b()}))):a.OnCompleted()}});return new q(f,c,L.Create(function(){e=!0}))})};g.Catch=function(){var b;b=
this;return h(function(a){var c,d,e,f,i;e=!1;d=b.GetEnumerator();f=new w;c=p.Immediate.ScheduleRecursive(function(b){var c,l,m;m=!1;if(!e){try{if(m=d.MoveNext())c=d.Current}catch(g){l=g}void 0!==l?a.OnError(l):m?(l=new s,f.Disposable(l),l.Disposable(c.Subscribe(function(b){a.OnNext(b)},function(a){i=a;b()},function(){a.OnCompleted()}))):void 0!==i?a.OnError(i):a.OnCompleted()}});return new q(f,c,L.Create(function(){e=!0}))})};var na=H.Repeat=function(b,a){void 0===a&&(a=-1);var c;c=new H;c.GetEnumerator=
function(){return{left:a,Current:null,MoveNext:function(){if(0===this.left)return this.Current=null,!1;0<this.left&&this.left--;this.Current=b;return!0}}};return c},ca=H.For=function(b){var a;a=new H;a.GetEnumerator=function(){return{_index:-1,Current:null,MoveNext:function(){if(++this._index<b.length)return this.Current=b[this._index],!0;this._index=-1;this.Current=null;return!1}}};return a},V,t;t=o.Observer=function(){};V=o.AbstractObserver=function(){function b(){this.isStopped=!1}r(b,t);b.prototype.OnNext=
function(a){this.isStopped||this.Next(a)};b.prototype.OnError=function(a){if(!this.isStopped)this.isStopped=!0,this.Error(a)};b.prototype.OnCompleted=function(){if(!this.isStopped)this.isStopped=!0,this.Completed()};b.prototype.Dispose=function(){this.isStopped=!0};return b}();var N;N=function(){function b(a,c,d){b.__super__.constructor.call(this);this.onNext=a;this.onError=c;this.onCompleted=d}r(b,V);b.prototype.Next=function(a){this.onNext(a)};b.prototype.Error=function(a){this.onError(a)};b.prototype.Completed=
function(){this.onCompleted()};return b}();var D;D=function(){function b(a,b){"function"===typeof a&&"function"===typeof b?(this.LeftObserver=oa(a),this.RightObserver=oa(b)):(this.LeftObserver=a,this.RightObserver=b)}r(b,t);b.prototype.OnNext=function(a){var b;b=this;return a.Switch(function(a){return a.Accept(b.LeftObserver)},function(a){return a.Accept(b.RightObserver)})};b.prototype.OnError=function(){};b.prototype.OnCompleted=function(){};return b}();var pa;pa=function(){function b(a,b){this.scheduler=
a;this.observer=b;this.hasFaulted=this.isAcquired=!1;this.queue=[];this.disposable=new w}r(b,V);b.prototype.EnsureActive=function(){var a,b;b=this;a=!1;if(!this.hasFaulted&&0<this.queue.length)a=!this.isAcquired,this.isAcquired=!0;a&&this.disposable.Disposable(this.scheduler.ScheduleRecursive(function(a){var e;if(0<b.queue.length){e=b.queue.shift();try{e()}catch(f){throw b.queue=[],b.hasFaulted=!0,f;}a()}else b.isAcquired=!1}))};b.prototype.Next=function(a){var b;b=this;this.queue.push(function(){b.observer.OnNext(a)})};
b.prototype.Error=function(a){var b;b=this;this.queue.push(function(){b.observer.OnError(a)})};b.prototype.Completed=function(){var a;a=this;this.queue.push(function(){a.observer.OnCompleted()})};b.prototype.Dispose=function(){b.__super__.Dispose.call(this);this.disposable.Dispose()};return b}();var I;I=t.Create=function(b,a,c){void 0===a&&(a=function(a){throw a;});void 0===c&&(c=function(){return{}});return new N(b,a,c)};t.FromNotifier=function(b){return new N(function(a){return b(n.CreateOnNext(a))},
function(a){return b(n.CreateOnError(a))},function(){return b(n.CreateOnCompleted())})};t.prototype.ToNotifier=function(){var b;b=this;return function(a){return a.Accept(b)}};t.prototype.AsObserver=function(){var b;b=this;return new N(function(a){return b.OnNext(a)},function(a){return b.OnError(a)},function(){return b.OnCompleted()})};var oa=function(b){return new N(function(a){b(n.CreateOnNext(a))},function(a){b(n.CreateOnError(a))},function(){b(n.CreateOnCompleted())})},qa,ra,k;k=o.Observable=function(){function b(){}
b.prototype.Subscribe=function(a,b,d){return this._Subscribe(0===arguments.length||1<arguments.length||"function"===typeof a?I(a,b,d):a)};return b}();g=k.prototype;qa=function(){function b(a){b.__super__.constructor.call(this);this.subscribe=a}r(b,k);b.prototype._Subscribe=function(a){var b,d;b=new ra(a);d=this;C.ScheduleRequired()?C.Schedule(function(){b.Disposable(d.subscribe(b))}):b.Disposable(d.subscribe(b));return b};return b}();ra=function(){function b(a){b.__super__.constructor.call(this);
this.observer=a;this.m=new s}r(b,V);b.prototype.Disposable=function(a){return a?this.m.Disposable(a):this.m.Disposable()};b.prototype.Next=function(a){this.observer.OnNext(a)};b.prototype.Error=function(a){this.observer.OnError(a);this.m.Dispose()};b.prototype.Completed=function(){this.observer.OnCompleted();this.m.Dispose()};b.prototype.Dispose=function(){b.__super__.Dispose.call(this);this.m.Dispose()};return b}();var da;da=function(){function b(a,c,d){b.__super__.constructor.call(this);this.Key=
a;this.underlyingObservable=void 0!==d?h(function(a){return new q(d.GetDisposable(),c.Subscribe(a))}):c}r(b,k);b.prototype._Subscribe=function(a){return this.underlyingObservable.Subscribe(a)};return b}();var sa;sa=o.ConnectableObservable=function(){function b(a,b){this.subject=b;this.source=a.AsObservable();this.hasSubscription=!1;this.subscription=null}r(b,k);b.prototype.Connect=function(){if(!this.hasSubscription){var a;a=this;this.hasSubscription=!0;this.subscription=new q(this.source.Subscribe(this.subject),
A(function(){a.hasSubscription=!1}))}return this.subscription};b.prototype.RefCount=function(){var a,b,d;d=this;b=0;a=null;return h(function(e){var f,i;b++;f=1===b;i=d.Subscribe(e);f&&(a=d.Connect());return A(function(){i.Dispose();b--;0===b&&a.Dispose()})})};b.prototype._Subscribe=function(a){return this.subject.Subscribe(a)};return b}();var x;x=o.Subject=function(){function b(){this.isStopped=this.isDisposed=!1;this.observers=new v;this.exception=void 0}r(b,k);b.prototype.OnCompleted=function(){var a,
b;this.CheckDisposed();if(!this.isStopped)a=this.observers.ToArray(),this.observers=new v,this.isStopped=!0;if(void 0!==a)for(b=0;b<a.length;b++)a[b].OnCompleted()};b.prototype.OnError=function(a){var b,d;this.CheckDisposed();if(!this.isStopped)b=this.observers.ToArray(),this.observers=new v,this.isStopped=!0,this.exception=a;if(void 0!==b)for(d=0;d<b.length;d++)b[d].OnError(a)};b.prototype.OnNext=function(a){var b,d;this.CheckDisposed();this.isStopped||(b=this.observers.ToArray());if(void 0!==b)for(d=
0;d<b.length;d++)b[d].OnNext(a)};b.prototype._Subscribe=function(a){this.CheckDisposed();if(!this.isStopped)return this.observers.Add(a),function(a,b){this.observer=b;this.Dispose=function(){if(null!==this.observer&&!a.isDisposed)a.observers.Remove(this.observer),this.observer=null}}(this,a);if(void 0!==this.exception)return a.OnError(this.exception),y;a.OnCompleted();return y};b.prototype.Unsubscribe=function(a){if(null!==this.observers)return this.observers.Remove(a)};b.prototype.CheckDisposed=
function(){if(this.isDisposed)throw"Object has been disposed";};b.prototype.Dispose=function(){this.isDisposed=!0;this.observers=null};return b}();x.prototype.ToNotifier=t.prototype.ToNotifier;x.prototype.AsObserver=t.prototype.AsObserver;var J;J=o.AsyncSubject=function(){function b(){this.isStopped=this.isDisposed=!1;this.value=null;this.hasValue=!1;this.observers=new v;this.exception=null}r(b,k);b.prototype.OnCompleted=function(){var a,b,d,e;a=!1;this.CheckDisposed();if(!this.isStopped)b=this.observers.ToArray(),
this.observers=new v,this.isStopped=!0,d=this.value,a=this.hasValue;if(void 0!==b)if(a)for(e=0;e<b.length;e++)a=b[e],a.OnNext(d),a.OnCompleted();else for(e=0;e<b.length;e++)b[e].OnCompleted()};b.prototype.OnError=function(a){var b,d;this.CheckDisposed();if(!this.isStopped)b=this.observers.ToArray(),this.observers=new v,this.isStopped=!0,this.exception=a;if(void 0!==b)for(d=0;d<b.length;d++)b[d].OnError(a)};b.prototype.OnNext=function(a){this.CheckDisposed();if(!this.isStopped)this.value=a,this.hasValue=
!0};b.prototype._Subscribe=function(a){var b,d,e;this.CheckDisposed();if(!this.isStopped)return this.observers.Add(a),function(a,b){this.observer=b;this.Dispose=function(){if(null!==this.observer&&!a.isDisposed)a.observers.Remove(this.observer),this.observer=null}}(this,a);b=this.exception;d=this.hasValue;e=this.value;null!==b?a.OnError(b):(d&&a.OnNext(e),a.OnCompleted());return y};b.prototype.CheckDisposed=function(){if(this.isDisposed)throw"Object has been disposed";};b.prototype.Dispose=function(){this.isDisposed=
!0;this.value=this.exception=this.observers=null};return b}();J.prototype.ToNotifier=t.prototype.ToNotifier;J.prototype.AsObserver=t.prototype.AsObserver;var O;O=o.BehaviorSubject=function(){function b(a){this.value=a;this.observers=new v;this.isStopped=this.isDisposed=!1;this.exception=null}r(b,k);b.prototype.OnCompleted=function(){var a,b;a=null;this._CheckDisposed();if(!this.isStopped)a=this.observers.ToArray(),this.observers=new v,this.isStopped=!0;if(null!==a)for(b=0;b<a.length;b++)a[b].OnCompleted()};
b.prototype.OnError=function(a){var b,d;d=null;this._CheckDisposed();if(!this.isStopped)d=this.observers.ToArray(),this.observers=new v,this.isStopped=!0,this.exception=a;if(null!==d)for(b=0;b<d.length;b++)d[b].OnError(a)};b.prototype.OnNext=function(a){var b,d;b=null;this._CheckDisposed();if(!this.isStopped)this.value=a,b=this.observers.ToArray();if(null!==b)for(d=0;d<b.length;d++)b[d].OnNext(a)};b.prototype._Subscribe=function(a){var b;this._CheckDisposed();if(!this.isStopped)return this.observers.Add(a),
a.OnNext(this.value),function(a,b){this.observer=b;this.Dispose=function(){if(null!==this.observer&&!a.isDisposed)a.observers.Remove(this.observer),this.observer=null}}(this,a);b=this.exception;null!==b?a.OnError(b):a.OnCompleted();return y};b.prototype._CheckDisposed=function(){if(this.isDisposed)throw"Object has been disposed";};b.prototype.Dispose=function(){this.isDisposed=!0;this.exception=this.value=this.observers=null};return b}();O.prototype.ToNotifier=t.prototype.ToNotifier;O.prototype.AsObserver=
t.prototype.AsObserver;var ta,P;P=o.ReplaySubject=function(){function b(a,b,d){this.bufferSize=void 0===a?Number.MAX_VALUE:a;this.window=void 0===b?Number.MAX_VALUE:b;this.scheduler=d||p.CurrentThread;this.q=[];this.observers=new v;this.isDisposed=this.isStopped=!1}r(b,k);b.prototype._Trim=function(a){var b,d;b=this.isStopped?1:0;d=b+this.bufferSize;if(d<this.bufferSize)d=this.bufferSize;for(;this.q.length>d;)this.q.shift();for(;this.q.length>b&&a-this.q[0].Timestamp>this.window;)this.q.shift()};
b.prototype._Enqueue=function(a){var b;b=this.scheduler.Now();this.q.push({Value:a,Timestamp:b});this._Trim(b)};b.prototype.OnNext=function(a){var b,d,e;b=null;this._CheckDisposed();if(!this.isStopped){b=this.observers.ToArray();this._Enqueue(n.CreateOnNext(a));for(e=0;e<b.length;e++)d=b[e],d.OnNext(a)}if(null!==b)for(e=0;e<b.length;e++)d=b[e],d.EnsureActive()};b.prototype.OnError=function(a){var b,d;b=null;this._CheckDisposed();if(!this.isStopped){this.isStopped=!0;this._Enqueue(n.CreateOnError(a));
b=this.observers.ToArray();for(d=0;d<b.length;d++)b[d].OnError(a);this.observers=new v}if(null!==b)for(d=0;d<b.length;d++)b[d].EnsureActive()};b.prototype.OnCompleted=function(){var a,b;a=null;this._CheckDisposed();if(!this.isStopped){this.isStopped=!0;this._Enqueue(n.CreateOnCompleted());a=this.observers.ToArray();for(b=0;b<a.length;b++)a[b].OnCompleted();this.observers=new v}if(null!==a)for(b=0;b<a.length;b++)a[b].EnsureActive()};b.prototype._Subscribe=function(a){var b,d,a=new pa(this.scheduler,
a);b=new ta(this,a);this._CheckDisposed();this._Trim(this.scheduler.Now());this.observers.Add(a);for(d=0;d<this.q.length;d++)this.q[d].Value.Accept(a);a.EnsureActive();return b};b.prototype._Unsubscribe=function(a){this.isDisposed||this.observers.Remove(a)};b.prototype.Dispose=function(){this.isDisposed=!0;this.observers=null};b.prototype._CheckDisposed=function(){if(this.isDisposed)throw"Object has been disposed";};return b}();ta=function(){function b(a,b){this.subject=a;this.observer=b}b.prototype.Dispose=
function(){this.observer.Dispose();this.subject._Unsubscribe(this.observer)};return b}();P.prototype.ToNotifier=t.prototype.ToNotifier;P.prototype.AsObserver=t.prototype.AsObserver;var W;W=function(){function b(a,b){this.observer=a;this.observable=b}r(b,k);b.prototype.OnCompleted=function(){return this.observer.OnCompleted()};b.prototype.OnError=function(a){return this.observer.OnError(a)};b.prototype.OnNext=function(a){return this.observer.OnNext(a)};b.prototype._Subscribe=function(a){return this.observable.Subscribe(a)};
return b}();W.prototype.ToNotifier=t.prototype.ToNotifier;W.prototype.AsObserver=t.prototype.AsObserver;x.Create=function(b,a){return new W(b,a)};var ua;k.Start=function(b,a,c,d){void 0===c&&(c=[]);return ua(b,d).apply(a,c)};ua=k.ToAsync=function(b,a){void 0===a&&(a=u);return function(){var c,d,e,f;f=new J;d=function(){var a;try{a=b.apply(this,arguments)}catch(c){f.OnError(c);return}f.OnNext(a);f.OnCompleted()};c=z.call(arguments);e=this;a.Schedule(function(){d.apply(e,c)});return f}};g.Multicast=
function(b,a){var c;c=this;return"function"===typeof b?h(function(d){var e;e=c.Multicast(b());return new q(a(e).Subscribe(d),e.Connect())}):new sa(c,b)};g.Publish=function(b){return void 0===b?this.Multicast(new x):this.Multicast(function(){return new x},b)};g.PublishLast=function(b){return void 0===b?this.Multicast(new J):this.Multicast(function(){return new J},b)};g.Replay=function(b,a,c,d){return void 0===b||null===b?this.Multicast(new P(a,c,d)):this.Multicast(function(){return new P(a,c,d)},b)};
g.PublishValue=function(b,a){return"function"===typeof b?this.Multicast(function(){return new O(a)},b):this.Multicast(new O(b))};var va=k.Never=function(){return h(function(){return y})};k.Empty=function(b){void 0===b&&(b=B);return h(function(a){return b.Schedule(function(){return a.OnCompleted()})})};var Ga=k.Return=function(b,a){void 0===a&&(a=B);return h(function(c){return a.Schedule(function(){c.OnNext(b);return c.OnCompleted()})})},wa=k.Throw=function(b,a){void 0===a&&(a=B);return h(function(c){return a.Schedule(function(){return c.OnError(b)})})},
Ha=k.Generate=function(b,a,c,d,e){void 0===e&&(e=C);return h(function(f){var i,j;j=b;i=!0;return e.ScheduleRecursive(function(b){var e,m;try{i?i=!1:j=c(j),(e=a(j))&&(m=d(j))}catch(g){f.OnError(g);return}e?(f.OnNext(m),b()):f.OnCompleted()})})},Q=k.Defer=function(b){return h(function(a){var c;try{c=b()}catch(d){return wa(d).Subscribe(a)}return c.Subscribe(a)})};k.Using=function(b,a){return h(function(c){var d,e,f;d=y;try{e=b(),null!==e&&(d=e),f=a(e)}catch(i){return new q(k.Throw(i).Subscribe(c),d)}return new q(f.Subscribe(c),
d)})};var xa=k.FromArray=function(b,a){void 0===a&&(a=C);return h(function(c){var d;d=0;return a.ScheduleRecursive(function(a){d<b.length?(c.OnNext(b[d++]),a()):c.OnCompleted()})})},h=k.CreateWithDisposable=function(b){return new qa(b)};k.Create=function(b){return h(function(a){return A(b(a))})};k.Range=function(b,a,c){var d;void 0===c&&(c=C);d=b+a-1;return Ha(b,function(a){return a<=d},function(a){return a+1},function(a){return a},c)};g.Repeat=function(b){return na(this,b).Concat()};g.Retry=function(b){return na(this,
b).Catch()};k.Repeat=function(b,a,c){void 0===a&&(a=-1);void 0===c&&(c=C);return Ga(b,c).Repeat(a)};g.Select=function(b){var a;a=this;return h(function(c){var d;d=0;return a.Subscribe(function(a){var f;try{f=b(a,d++)}catch(i){c.OnError(i);return}c.OnNext(f)},function(a){c.OnError(a)},function(){c.OnCompleted()})})};g.Where=function(b){var a;a=this;return h(function(c){var d;d=0;return a.Subscribe(function(a){var f;try{f=b(a,d++)}catch(i){c.OnError(i);return}f&&c.OnNext(a)},function(a){c.OnError(a)},
function(){c.OnCompleted()})})};g.GroupByUntil=function(b,a,c,d){var e;e=this;void 0===a&&(a=T);void 0===d&&(d=Z);return h(function(f){var i,j,g;j={};i=new q;g=new M(i);i.Add(e.Subscribe(function(e){var m,h,k,q,R,S,p,o,n;try{h=b(e),S=d(h)}catch(r){for(n in j)j[n].OnError(r);f.OnError(r);return}R=!1;try{o=j[S],void 0===o&&(o=new x,j[S]=o,R=!0)}catch(t){for(n in j)j[n].OnError(t);f.OnError(t);return}if(R){R=new da(h,o,g);h=new da(h,o);try{m=c(h)}catch(u){for(n in j)j[n].OnError(u);f.OnError(u);return}f.OnNext(R);
p=new s;i.Add(p);q=function(){void 0!==j[S]&&(delete j[S],o.OnCompleted());i.Remove(p)};p.Disposable(m.Take(1).Subscribe(function(){},function(a){for(n in j)j[n].OnError(a);f.OnError(a)},function(){q()}))}try{k=a(e)}catch(v){for(n in j)j[n].OnError(v);f.OnError(v);return}o.OnNext(k)},function(a){for(var b in j)j[b].OnError(a);f.OnError(a)},function(){for(var a in j)j[a].OnCompleted();f.OnCompleted()}));return g})};g.GroupBy=function(b,a,c){return this.GroupByUntil(b,a,function(){return va()},c)};
g.Take=function(b){if(0>=b)throw"Argument out of range";var a;a=this;return h(function(c){var d;d=b;return a.Subscribe(function(a){0<d&&(d--,c.OnNext(a),0===d&&c.OnCompleted())},function(a){return c.OnError(a)},function(){return c.OnCompleted()})})};g.Skip=function(b){if(0>b)throw"Argument out of range";var a;a=this;return h(function(c){var d;d=b;return a.Subscribe(function(a){0>=d?c.OnNext(a):d--},function(a){return c.OnError(a)},function(){return c.OnCompleted()})})};g.TakeWhile=function(b){var a;
a=this;return h(function(c){var d,e;e=!0;d=0;return a.Subscribe(function(a){if(e){try{e=b(a,d++)}catch(i){c.OnError(i);return}e?c.OnNext(a):c.OnCompleted()}},function(a){return c.OnError(a)},function(){return c.OnCompleted()})})};g.SkipWhile=function(b){var a;a=this;return h(function(c){var d,e;e=!1;d=0;return a.Subscribe(function(a){if(!e)try{e=!b(a,d++)}catch(i){c.OnError(i);return}e&&c.OnNext(a)},function(a){c.OnError(a)},function(){c.OnCompleted()})})};g.SelectMany=function(b,a){return void 0!==
a?this.SelectMany(function(c){return b(c).Select(function(b){return a(c,b)})}):"function"===typeof b?this.Select(b).MergeObservable():this._SelectMany(function(){return b})};var ya,X;ya=function(b){return h(function(a){var c,d;c=!1;return b.Subscribe(function(a){c=!0;d=a},function(b){a.OnError(b)},function(){c?(a.OnNext(d),a.OnCompleted()):a.OnError("Sequence contains no elements.")})})};X=function(b){return ya(b.Scan([],function(a,b){a.push(b);return a}).StartWith([]))};g.Materialize=function(){var b;
b=this;return h(function(a){return b.Subscribe(function(b){a.OnNext(n.CreateOnNext(b))},function(b){a.OnNext(n.CreateOnError(b));a.OnCompleted()},function(){a.OnNext(n.CreateOnCompleted());a.OnCompleted()})})};g.Dematerialize=function(){var b;b=this;return h(function(a){return b.Subscribe(function(b){return b.Accept(a)},a.OnError,a.OnCompleted)})};g.AsObservable=function(){var b;b=this;return h(function(a){return b.Subscribe(a)})};g.WindowWithCount=function(b,a){var c;c=this;if(0>=b)throw"Argument out of range";
void 0===a&&(a=b);if(0>=a)throw"Argument out of range";return h(function(d){var e,f,i,j,g;j=[];i=0;f=new s;g=new M(f);e=function(){var a;a=new x;j.push(a);d.OnNext(a.AddRef(g))};e();f.Disposable(c.Subscribe(function(c){var d;for(d=0;d<j.length;d++)j[d].OnNext(c);c=i-b+1;0<=c&&0===c%a&&(c=j.shift(),c.OnCompleted());i++;0===i%a&&e()},function(a){for(;0<j.length;)j.shift().OnError(a);return d.OnError(a)},function(){for(;0<j.length;)j.shift().OnCompleted();d.OnCompleted()}));return g})};g.BufferWithCount=
function(b,a){void 0===a&&(a=b);return this.WindowWithCount(b,a).SelectMany(function(a){return X(a)}).Where(function(a){return 0<a.length})};g.StartWith=function(){var b,a;b=0;0<arguments.length&&void 0!==arguments[0].Now?(a=arguments[0],b=1):a=B;b=z.call(arguments,b);return ca([xa(b,a),this]).Concat()};g.Scan=function(b,a){var c;c=this;return Q(function(){var d,e;d=!1;return c.Select(function(c){d?e=a(e,c):(e=a(b,c),d=!0);return e})})};g.Scan1=function(b){var a;a=this;return Q(function(){var c,d;
c=!1;return a.Select(function(a){c?d=b(d,a):(d=a,c=!0);return d})})};g.DistinctUntilChanged=function(b,a){var c;void 0==b&&(b=T);void 0===a&&(a=Y);c=this;return h(function(d){var e,f;e=!1;return c.Subscribe(function(c){var j,g;try{g=b(c)}catch(l){d.OnError(l);return}j=!1;if(e)try{j=a(f,g)}catch(m){d.OnError(m);return}if(!e||!j)e=!0,f=g,d.OnNext(c)},function(a){d.OnError(a)},function(){d.OnCompleted()})})};g.Finally=function(b){var a;a=this;return h(function(c){var d;d=a.Subscribe(c);return A(function(){try{d.Dispose()}finally{b()}})})};
g.Do=function(b,a,c){var d,e;d=this;0==arguments.length||1<arguments.length||"function"==typeof b?e=b:(e=function(a){b.OnNext(a)},a=function(a){b.OnError(a)},c=function(){b.OnCompleted()});return h(function(b){return d.Subscribe(function(a){try{e(a)}catch(c){b.OnError(c)}b.OnNext(a)},function(c){if(void 0!==a)try{a(c)}catch(d){b.OnError(d)}b.OnError(c)},function(){if(void 0!==c)try{c()}catch(a){b.OnError(a)}b.OnCompleted()})})};g.SkipLast=function(b){var a;a=this;return h(function(c){var d;d=[];return a.Subscribe(function(a){d.push(a);
d.length>b&&c.OnNext(d.shift())},function(a){c.OnError(a)},function(){c.OnCompleted()})})};g.TakeLast=function(b){var a;a=this;return h(function(c){var d;d=[];return a.Subscribe(function(a){d.push(a);d.length>b&&d.shift()},function(a){c.OnError(a)},function(){for(;0<d.length;)c.OnNext(d.shift());c.OnCompleted()})})};g.IgnoreElements=function(){var b;b=this;return h(function(a){return b.Subscribe(ia,function(b){a.OnError(b)},function(){a.OnCompleted()})})};g.ElementAt=function(b){var a;a=this;if(0>
b)throw"Argument out of range";return h(function(c){var d;d=b;return a.Subscribe(function(a){0===d&&(c.OnNext(a),c.OnCompleted());return d--},function(a){c.OnError(a)},function(){c.OnError("Argument out of range")})})};g.ElementAtOrDefault=function(b,a){var c;c=this;if(0>b)throw"Argument out of range";void 0===a&&(a=null);return h(function(d){var e;e=b;return c.Subscribe(function(a){0===e&&(d.OnNext(a),d.OnCompleted());e--},function(a){d.OnError(a)},function(){d.OnNext(a);d.OnCompleted()})})};g.DefaultIfEmpty=
function(b){var a;void 0===b&&(b=null);a=this;return h(function(c){var d;d=!1;return a.Subscribe(function(a){d=!0;return c.OnNext(a)},function(a){c.OnError(a)},function(){d||c.OnNext(b);c.OnCompleted()})})};g.Distinct=function(b,a){var c;void 0===b&&(b=T);void 0===a&&(a=Z);c=this;return h(function(d){var e;e={};return c.Subscribe(function(c){var i,j,g,l;l=!1;try{i=b(c),j=a(i)}catch(m){d.OnError(m);return}for(g in e)if(j===g){l=!0;break}l||(e[j]=null,d.OnNext(c))},function(a){d.OnError(a)},function(){d.OnCompleted()})})};
g.MergeObservable=function(){var b;b=this;return h(function(a){var c,d,e;d=!1;e=new s;c=new q;c.Add(e);e.Disposable(b.Subscribe(function(b){var e;e=new s;c.Add(e);e.Disposable(b.Subscribe(function(b){a.OnNext(b)},function(b){a.OnError(b)},function(){c.Remove(e);d&&1===c.Count()&&a.OnCompleted()}))},function(b){a.OnError(b)},function(){d=!0;1===c.Count()&&a.OnCompleted()}));return c})};g.Merge=function(b){var a;a=this;return h(function(c){var d,e,f,i,j;i=[];f=!1;e=new q;d=0;j=function(a){var b;b=new s;
e.Add(b);b.Disposable(a.Subscribe(function(a){c.OnNext(a)},function(a){c.OnError(a)},function(){var a;e.Remove(b);0<i.length?(a=i.shift(),j(a)):(d--,f&&0===d&&c.OnCompleted())}))};e.Add(a.Subscribe(function(a){d<b?(d++,j(a)):i.push(a)},function(a){c.OnError(a)},function(){f=!0;0===d&&c.OnCompleted()}));return e})};g.Switch=function(){var b;b=this;return h(function(a){var c,d,e,f,i;d=new w;e=!1;f=0;c=!1;i=b.Subscribe(function(b){var i,g;g=++f;c=!0;i=new s;d.Disposable(i);return i.Disposable(b.Subscribe(function(b){f===
g&&a.OnNext(b)},function(b){f===g&&a.Error(b)},function(){f===g&&(c=!1,e&&a.OnCompleted())}))},function(b){a.OnError(b)},function(){e=!0;c||a.OnCompleted()});return new q(i,d)})};k.Merge=function(b){void 0===b&&(b=B);var a;a=1<arguments.length&&arguments[1]instanceof Array?arguments[1]:z.call(arguments,1);return xa(a,b).MergeObservable()};g._Shift=function(b,a){var c;c=ja(a);c.unshift(this);return b.apply(this,c)};g.Concat=function(){return this._Shift(Ia,arguments)};g.ConcatObservable=function(){return this.Merge(1)};
var Ia=k.Concat=function(){var b;b=1===arguments.length&&arguments[0]instanceof Array?arguments[0]:z.call(arguments,0);return ca(b).Concat()};g.Catch=function(b){return"function"===typeof b?Ja(this,b):Ka([this,b])};var Ja=function(b,a){return h(function(c){var d;d=new w;(new s).Disposable(b.Subscribe(function(a){c.OnNext(a)},function(b){var f;try{f=a(b)}catch(i){c.OnError(i);return}b=new s;d.Disposable(b);b.Disposable(f.Subscribe(c))},function(){c.OnCompleted()}));return d})},Ka=k.Catch=function(){var b;
b=1===arguments.length&&arguments[0]instanceof Array?arguments[0]:z.call(arguments);return ca(b).Catch()};g.OnErrorResumeNext=function(b){return La([this,b])};var La=k.OnErrorResumeNext=function(){var b;if(1===arguments.length&&arguments[0]instanceof Array)b=arguments[0];else{var a,c;b=[];for(a=0,c=arguments.length;a<c;a++)b.push(arguments[a])}return h(function(a){var c,f,i;f=0;i=new w;c=B.ScheduleRecursive(function(c){var e,g;f<b.length?(e=b[f++],g=new s,i.Disposable(g),g.Disposable(e.Subscribe(function(b){a.OnNext(b)},
function(){c()},function(){c()}))):a.OnCompleted()});return new q(i,c)})};g._Combine=function(b,a){var c;c=this;return h(function(d){var e,f;e=new s;f=new s;d=a(d,e,f);e.Disposable(c.Materialize().Select(function(a){return{Switch:function(b){return b(a)}}}).Subscribe(d));f.Disposable(b.Materialize().Select(function(a){return{Switch:function(b,c){return c(a)}}}).Subscribe(d));return new q(e,f)})};var za;za=function(){function b(a,b){var d;d=this;this.selector=a;this.observer=b;this.leftQ=[];this.rightQ=
[];this.Left=I(function(a){"E"===a.Kind()?d.observer.OnError(a.Exception()):0===d.rightQ.length?d.leftQ.push(a):d.OnNext(a,d.rightQ.shift())});this.Right=I(function(a){"E"===a.Kind()?d.observer.OnError(a.Exception()):0===d.leftQ.length?d.rightQ.push(a):d.OnNext(d.leftQ.shift(),a)})}b.prototype.OnNext=function(a,b){var d;if("C"===a.Kind()||"C"===b.Kind())this.observer.OnCompleted();else{try{d=this.selector(a.Value(),b.Value())}catch(e){this.observer.OnError(e);return}this.observer.OnNext(d)}};return b}();
g.Zip=function(b,a){return this._Combine(b,function(b){var d;d=new za(a,b);return new D(function(a){return d.Left.OnNext(a)},function(a){return d.Right.OnNext(a)})})};var Aa;Aa=function(){function b(a,b){var d;this.selector=a;this.observer=b;d=this;this.rightStopped=this.leftStopped=!1;this.Left=I(function(a){"N"===a.Kind()?(d.leftValue=a,void 0!==d.rightValue?d.OnNext():d.rightStopped&&d.observer.OnCompleted()):"E"===a.Kind()?d.observer.OnError(a.Exception()):(d.leftStopped=!0,d.rightStopped&&d.observer.OnCompleted())});
this.Right=I(function(a){"N"===a.Kind()?(d.rightValue=a,void 0!==d.leftValue?d.OnNext():d.leftStopped&&d.observer.OnCompleted()):"E"===a.Kind()?d.observer.OnError(a.Exception()):(d.rightStopped=!0,d.leftStopped&&d.observer.OnCompleted())})}b.prototype.OnNext=function(){var a;try{a=this.selector(this.leftValue.Value(),this.rightValue.Value())}catch(b){this.observer.OnError(b);return}this.observer.OnNext(a)};return b}();g.CombineLatest=function(b,a){return this._Combine(b,function(b){var d;d=new Aa(a,
b);return new D(function(a){return d.Left.OnNext(a)},function(a){return d.Right.OnNext(a)})})};g.TakeUntil=function(b){return b._Combine(this,function(a,b){var d,e;d=e=!1;return new D(function(b){!e&&!d&&("C"===b.Kind()?d=!0:"E"===b.Kind()?(e=d=!0,a.OnError(b.Exception())):(e=!0,a.OnCompleted()))},function(d){e||(d.Accept(a),(e="N"!==d.Kind())&&b.Dispose())})})};g.SkipUntil=function(b){return this._Combine(b,function(a,b,d){var e,f;f=e=!1;return new D(function(b){e&&b.Accept(a)},function(b){f||("N"===
b.Kind()?e=!0:"E"===b.Kind()&&a.OnError(b.Exception()),f=!0,d.Dispose())})})};k.Amb=function(){var b,a,c,d;c=1===arguments.length&&arguments[0]instanceof Array?arguments[0]:z.call(arguments);b=va();a=function(a,b){return a.Amb(b)};for(d=0;d<c.length;d++)b=a(b,c[d]);return b};g.Amb=function(b){return this._Combine(b,function(a,b,d){var e;e="N";return new D(function(b){"N"===e&&(e="L",d.Dispose());"L"===e&&b.Accept(a)},function(d){"N"===e&&(e="R",b.Dispose());"R"===e&&d.Accept(a)})})};var ea,Ba,fa,
Ca,ga;ea=function(b){return 0>b?0:b};Ba=function(b,a){return h(function(c){return a.ScheduleWithAbsolute(b,function(){c.OnNext(0);c.OnCompleted()})})};fa=function(b,a,c){var d;d=ea(a);return h(function(a){var f,i;i=b;f=0;return c.ScheduleRecursiveWithAbsolute(i,function(b){var g;0<d&&(g=c.Now(),i+=d,i<=g&&(i=g+d));a.OnNext(f++);b(i)})})};Ca=function(b,a){var c;c=ea(b);return h(function(b){return a.ScheduleWithRelative(c,function(){b.OnNext(0);b.OnCompleted()})})};ga=function(b,a,c){return Q(function(){return fa(c.Now()+
b,a,c)})};var Ma=k.Interval=function(b,a){void 0===a&&(a=u);return ga(b,b,a)};k.Timer=function(b,a,c){var d;void 0===c&&(c=u);void 0!==a&&"number"===typeof a?d=a:void 0!==a&&"object"===typeof a&&(c=a);return b instanceof Date&&void 0===d?Ba(b.getTime(),c):b instanceof Date&&void 0!==d?fa(b.getTime(),a,c):void 0===d?Ca(b,c):ga(b,d,c)};var Da,ha;ha=function(b,a,c){return h(function(d){var e,f,i,g,h,l;g=[];h=e=!1;f=new w;i=null;l=b.Materialize().Timestamp(c).Subscribe(function(b){"E"===b.Value.Kind()?
(g=[],g.push(b),i=b.Value.Exception(),b=!h):(g.push({Value:b.Value,Timestamp:b.Timestamp+a}),b=!e,e=!0);b&&(null!==i?d.OnError(i):(b=new s,f.Disposable(b),b.Disposable(c.ScheduleRecursiveWithRelative(a,function(a){var b,f,l;if(null===i){h=!0;do{b=null;if(0<g.length&&0>=g[0].Timestamp-c.Now())b=g.shift().Value;null!==b&&b.Accept(d)}while(null!==b);l=!1;f=0;0<g.length?(l=!0,f=Math.max(0,g[0].Timestamp-c.Now())):e=!1;b=i;h=!1;null!==b?d.OnError(b):l&&a(f)}}))))});return new q(l,f)})};Da=function(b,a,
c){return Q(function(){var b;b=a-c.Now();return ha(b,c)})};g.Delay=function(b,a){void 0===a&&(a=u);return b instanceof Date?Da(this,b.getTime(),a):ha(this,b,a)};g.Throttle=function(b,a){void 0===a&&(a=u);var c;c=this;return h(function(d){var e,f,g,j,h;h=null;f=!1;e=new w;g=0;j=c.Subscribe(function(c){var j;f=!0;h=c;g++;j=g;c=new s;e.Disposable(c);c.Disposable(a.ScheduleWithRelative(b,function(){f&&g===j&&d.OnNext(h);f=!1}))},function(a){e.Dispose();d.OnError(a);f=!1;g++},function(){e.Dispose();f&&
d.OnNext(h);d.OnCompleted();f=!1;g++});return new q(j,e)})};g.WindowWithTime=function(b,a,c){var d,e;d=this;void 0===a&&(e=b);void 0===c&&(c=u);"number"===typeof a?e=a:"object"===typeof a&&(e=b,c=a);return h(function(a){var g,j,h,l,m,k,n,o;o=0;h=e;l=b;m=[];n=new w;j=new q(n);k=new M(j);g=function(){var b,d,j,p,q;j=new s;n.Disposable(j);b=d=!1;l===h?b=d=!0:l<h?d=!0:b=!0;p=d?l:h;q=p-o;o=p;d&&(l+=e);b&&(h+=e);j.Disposable(c.ScheduleWithRelative(q,function(){var c;b&&(c=new x,m.push(c),a.OnNext(c.AddRef(k)));
d&&(c=m.shift(),c.OnCompleted());g()}))};m.push(new x);a.OnNext(m[0].AddRef(k));g();j.Add(d.Subscribe(function(a){var b,c;for(b=0;b<m.length;b++)c=m[b],c.OnNext(a)},function(b){var c,d;for(c=0;c<m.length;c++)d=m[c],d.OnError(b);a.OnError(b)},function(){var b,c;for(b=0;b<m.length;b++)c=m[b],c.OnCompleted();a.OnCompleted()}));return k})};g.WindowWithTimeOrCount=function(b,a,c){var d;d=this;void 0===c&&(c=u);return h(function(e){var f,g,j,h,l,m,k;k=j=0;m=new w;g=new q(m);h=new M(g);f=function(a){var d;
d=new s;m.Disposable(d);d.Disposable(c.ScheduleWithRelative(b,function(){var b;a===k&&(j=0,b=++k,l.OnCompleted(),l=new x,e.OnNext(l.AddRef(h)),f(b))}))};l=new x;e.OnNext(l.AddRef(h));f(0);g.Add(d.Subscribe(function(b){var c,d;d=!1;c=0;l.OnNext(b);j++;j===a&&(d=!0,j=0,c=++k,l.OnCompleted(),l=new x,e.OnNext(l.AddRef(h)));d&&f(c)},function(a){l.OnError(a);e.OnError(a)},function(){l.OnCompleted();e.OnCompleted()}));return h})};g.BufferWithTime=function(b,a,c){var d;void 0===a&&(d=b);void 0===c&&(c=u);
"number"===typeof a?d=a:"object"===typeof a&&(d=b,c=a);return this.WindowWithTime(b,d,c).SelectMany(function(a){return X(a)})};g.BufferWithTimeOrCount=function(b,a,c){void 0===c&&(c=u);return this.WindowWithTimeOrCount(b,a,c).SelectMany(function(a){return X(a)})};g.AddRef=function(b){var a;a=this;return h(function(c){return new q(b.GetDisposable(),a.Subscribe(c))})};g.TimeInterval=function(b){var a;a=this;void 0===b&&(b=u);return Q(function(){var c;c=b.Now();return a.Select(function(a){var e,f;e=
b.Now();f=e-c;c=e;return{Value:a,Interval:f}})})};g.Timestamp=function(b){void 0===b&&(b=u);return this.Select(function(a){return{Value:a,Timestamp:b.Now()}})};var Ea=function(b,a){return b._Combine(a,function(a){var b,e;b=!1;return new D(function(f){"N"===f.Kind()&&(e=f);"E"===f.Kind()&&f.Accept(a);"C"===f.Kind()&&(b=!0)},function(){var f;f=e;e=void 0;void 0!==f&&f.Accept(a);b&&a.OnCompleted()})})};g.Sample=function(b,a){void 0===a&&(a=u);return"number"===typeof b?Ea(this,Ma(b,a)):Ea(this,b)};g.Timeout=
function(b,a,c){var d,e;e=this;void 0===a&&(a=wa("Timeout"));void 0===c&&(c=u);d=b instanceof Date?function(a,b){c.ScheduleWithAbsolute(a,b)}:function(a,b){c.ScheduleWithRelative(a,b)};return h(function(c){var g,h,k,l,m,n;l=new w;n=new w;k=new s;l.Disposable(k);h=0;m=!1;g=function(){var e;e=h;n.Disposable(d(b,function(){(m=h===e)&&l.Disposable(a.Subscribe(c))}))};g();k.Disposable(e.Subscribe(function(a){m||(h++,c.OnNext(a),g())},function(a){m||(h++,c.OnError(a))},function(){m||(h++,c.OnCompleted())}));
return new q(l,n)})};k.GenerateWithAbsoluteTime=function(b,a,c,d,e,f){void 0===f&&(f=u);return h(function(g){var h,k,l,m,n;m=b;h=!0;k=!1;return f.ScheduleRecursiveWithAbsolute(f.Now(),function(b){k&&g.OnNext(l);try{if(h?h=!1:m=c(m),k=a(m))l=d(m),n=e(m)}catch(f){g.OnError(f);return}k?b(n):g.OnCompleted()})})};k.GenerateWithRelativeTime=function(b,a,c,d,e,f){void 0===f&&(f=u);return h(function(g){var h,k,l,m,n;m=b;h=!0;k=!1;return f.ScheduleRecursiveWithRelative(0,function(b){k&&g.OnNext(l);try{if(h?
h=!1:m=c(m),k=a(m))l=d(m),n=e(m)}catch(f){g.OnError(f);return}k?b(n):g.OnCompleted()})})}})();
